-- SUPABASE SCHEMA DEFINITION: WOW SALON ADMIN V2 (PRODUCTION READY)
-- Execute this entire script in the Supabase SQL Editor.

--------------------------------------------------------
-- 1. DROP EXISTING TABLES & TYPES
--------------------------------------------------------
DROP TABLE IF EXISTS public.staff_commissions CASCADE;
DROP TABLE IF EXISTS public.visit_products CASCADE;
DROP TABLE IF EXISTS public.visit_services CASCADE;
DROP TABLE IF EXISTS public.customer_visits CASCADE;
DROP TABLE IF EXISTS public.expenses CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.staff CASCADE;
DROP TABLE IF EXISTS public.services CASCADE;
DROP TABLE IF EXISTS public.customer_rewards CASCADE;
DROP TABLE IF EXISTS public.package_services CASCADE;
DROP TABLE IF EXISTS public.packages CASCADE;
DROP TABLE IF EXISTS public.customers CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

DROP TYPE IF EXISTS public.user_role CASCADE;

--------------------------------------------------------
-- 2. CREATE ENUMS, EXTENSIONS & TRIGGERS
--------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE public.user_role AS ENUM ('Owner', 'Manager', 'Receptionist');

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

--------------------------------------------------------
-- 3. CREATE PROFILES TABLE & HELPER FUNCTIONS
--------------------------------------------------------

-- Profiles (Linked to auth.users)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  role public.user_role NOT NULL DEFAULT 'Receptionist',
  email TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- These helper functions allow RLS policies to easily check the user's role without recursive queries.
CREATE OR REPLACE FUNCTION public.is_owner() RETURNS BOOLEAN AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'Owner');
$$ LANGUAGE sql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_manager() RETURNS BOOLEAN AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Owner', 'Manager'));
$$ LANGUAGE sql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.is_receptionist() RETURNS BOOLEAN AS $$
  SELECT EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role IN ('Owner', 'Manager', 'Receptionist'));
$$ LANGUAGE sql SECURITY DEFINER;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Owner can view all profiles" ON public.profiles FOR SELECT USING (public.is_owner());
CREATE POLICY "Owner can update profiles" ON public.profiles FOR UPDATE USING (public.is_owner());

-- Trigger to automatically create a profile for new users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  -- Defaulting to Owner for the first user to allow full access, 
  -- subsequent users can be changed in the dashboard
  VALUES (new.id, new.email, 'Owner');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop trigger if exists to prevent errors on re-run
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

--------------------------------------------------------
-- 4. CREATE CORE ENTITY TABLES
--------------------------------------------------------
-- Customers Table
CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT,
    dob DATE,
    services_taken TEXT[],
    staff_served TEXT[],
    amount_paid NUMERIC DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_customers_updated_at BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.customers FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow insert for all staff" ON public.customers FOR INSERT WITH CHECK (public.is_receptionist());
CREATE POLICY "Allow update for all staff" ON public.customers FOR UPDATE USING (public.is_receptionist());
CREATE POLICY "Allow delete for Owner and Manager" ON public.customers FOR DELETE USING (public.is_manager());

-- Customer Rewards
CREATE TABLE public.customer_rewards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE CASCADE,
    points INTEGER DEFAULT 0,
    membership_tier TEXT DEFAULT 'Standard',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_rewards_updated_at BEFORE UPDATE ON public.customer_rewards FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.customer_rewards ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.customer_rewards FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow insert/update for Manager" ON public.customer_rewards FOR ALL USING (public.is_manager());

-- Services Table
CREATE TABLE public.services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_name TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'Other',
    price NUMERIC NOT NULL DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_services_updated_at BEFORE UPDATE ON public.services FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.services FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow edit for Manager" ON public.services FOR ALL USING (public.is_manager());

-- Packages
CREATE TABLE public.packages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_packages_updated_at BEFORE UPDATE ON public.packages FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.packages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.packages FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow edit for Manager" ON public.packages FOR ALL USING (public.is_manager());

-- Package Services Mapping
CREATE TABLE public.package_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    package_id BIGINT REFERENCES public.packages(id) ON DELETE CASCADE,
    service_id BIGINT REFERENCES public.services(id) ON DELETE CASCADE
);
ALTER TABLE public.package_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.package_services FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow edit for Manager" ON public.package_services FOR ALL USING (public.is_manager());

-- Staff Table
CREATE TABLE public.staff (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    gender TEXT,
    salary NUMERIC DEFAULT 0,
    commission_rate NUMERIC DEFAULT 10, -- Default 10%
    service_revenue NUMERIC DEFAULT 0,
    commission_earned NUMERIC DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_staff_updated_at BEFORE UPDATE ON public.staff FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.staff ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.staff FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow edit for Manager" ON public.staff FOR ALL USING (public.is_manager());

-- Products (Inventory) Table
CREATE TABLE public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    purchase_price NUMERIC NOT NULL DEFAULT 0,
    selling_price NUMERIC NOT NULL DEFAULT 0,
    purchased_quantity INTEGER NOT NULL DEFAULT 0,
    sold_quantity INTEGER NOT NULL DEFAULT 0,
    salon_consumption INTEGER NOT NULL DEFAULT 0,
    current_stock INTEGER NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_products_updated_at BEFORE UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.products FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow insert/update for Manager" ON public.products FOR INSERT WITH CHECK (public.is_manager());
CREATE POLICY "Allow update for Manager" ON public.products FOR UPDATE USING (public.is_manager());
CREATE POLICY "Allow delete for Owner" ON public.products FOR DELETE USING (public.is_owner());

-- Expenses Table
CREATE TABLE public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    title TEXT,
    category TEXT NOT NULL CHECK (category IN ('Electricity', 'Water', 'Rent', 'Internet', 'Salary', 'Inventory', 'Other Expenses')),
    amount NUMERIC NOT NULL DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_expenses_updated_at BEFORE UPDATE ON public.expenses FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Owner read access" ON public.expenses FOR SELECT USING (public.is_owner());
CREATE POLICY "Manager read access" ON public.expenses FOR SELECT USING (public.is_manager());
CREATE POLICY "Manager insert access" ON public.expenses FOR INSERT WITH CHECK (public.is_manager());
CREATE POLICY "Manager update access" ON public.expenses FOR UPDATE USING (public.is_manager());
CREATE POLICY "Owner delete access" ON public.expenses FOR DELETE USING (public.is_owner());

--------------------------------------------------------
-- 5. CREATE TRANSACTION & MAPPING TABLES
--------------------------------------------------------

-- Customer Visits (Master Transaction Record)
CREATE TABLE public.customer_visits (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers(id) ON DELETE SET NULL,
    visit_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    service_total NUMERIC DEFAULT 0,
    product_total NUMERIC DEFAULT 0,
    grand_total NUMERIC DEFAULT 0,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE SET NULL,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_visits_updated_at BEFORE UPDATE ON public.customer_visits FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.customer_visits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read for all staff" ON public.customer_visits FOR SELECT USING (public.is_receptionist());
CREATE POLICY "Allow insert for all staff" ON public.customer_visits FOR INSERT WITH CHECK (public.is_receptionist());
CREATE POLICY "Allow update for all staff" ON public.customer_visits FOR UPDATE USING (public.is_receptionist());
CREATE POLICY "Allow delete for Owner" ON public.customer_visits FOR DELETE USING (public.is_owner());

-- Visit Services Mapping
CREATE TABLE public.visit_services (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    service_id BIGINT REFERENCES public.services(id) ON DELETE SET NULL,
    service_name TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0
);
ALTER TABLE public.visit_services ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for staff" ON public.visit_services FOR ALL USING (public.is_receptionist());

-- Visit Products Mapping
CREATE TABLE public.visit_products (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 1,
    price NUMERIC NOT NULL DEFAULT 0
);
ALTER TABLE public.visit_products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all for staff" ON public.visit_products FOR ALL USING (public.is_receptionist());

-- Staff Commissions Table
CREATE TABLE public.staff_commissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    staff_id BIGINT REFERENCES public.staff(id) ON DELETE CASCADE,
    visit_id UUID REFERENCES public.customer_visits(id) ON DELETE CASCADE,
    service_amount NUMERIC NOT NULL DEFAULT 0,
    commission_amount NUMERIC NOT NULL DEFAULT 0,
    is_deleted BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
CREATE TRIGGER update_commissions_updated_at BEFORE UPDATE ON public.staff_commissions FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
ALTER TABLE public.staff_commissions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Manager read access" ON public.staff_commissions FOR SELECT USING (public.is_manager());
CREATE POLICY "Staff all access" ON public.staff_commissions FOR ALL USING (public.is_receptionist()); -- Needs insert/update for visits

--------------------------------------------------------
-- 6. CREATE INDEXES FOR PERFORMANCE
--------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_customers_phone ON public.customers(phone);
CREATE INDEX IF NOT EXISTS idx_customers_name ON public.customers(name);
CREATE INDEX IF NOT EXISTS idx_customers_is_deleted ON public.customers(is_deleted);

CREATE INDEX IF NOT EXISTS idx_visits_date ON public.customer_visits(visit_date);
CREATE INDEX IF NOT EXISTS idx_visits_customer_id ON public.customer_visits(customer_id);
CREATE INDEX IF NOT EXISTS idx_visits_staff_id ON public.customer_visits(staff_id);
CREATE INDEX IF NOT EXISTS idx_visits_is_deleted ON public.customer_visits(is_deleted);

CREATE INDEX IF NOT EXISTS idx_visit_services_visit_id ON public.visit_services(visit_id);
CREATE INDEX IF NOT EXISTS idx_visit_products_visit_id ON public.visit_products(visit_id);

CREATE INDEX IF NOT EXISTS idx_commissions_staff_id ON public.staff_commissions(staff_id);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON public.expenses(date);
CREATE INDEX IF NOT EXISTS idx_products_name ON public.products(name);

--------------------------------------------------------
-- 7. SEED DEFAULT DATA
--------------------------------------------------------

INSERT INTO public.services (service_name, category, price) VALUES 
-- Haircut service
('Hair wash', 'Haircut', 200),
('Hairwash with blow dry', 'Haircut', 400),
('Premium hair wash', 'Haircut', 500),
('Ironing', 'Haircut', 500),
('Tong', 'Haircut', 700),
('Crimping', 'Haircut', 700),
('Normal haircut', 'Haircut', 700),
('Premium haircut', 'Haircut', 1500),

-- Hair colour service
('Root touch-up (Ammonia)', 'Hair colour', 1500),
('Root touch-up (Ammonia free)', 'Hair colour', 2000),
('Global colour (Ammonia)', 'Hair colour', 3000),
('Global colour (Ammonia free)', 'Hair colour', 4000),
('Highlights (Classic)', 'Hair colour', 5000),
('Highlights with global', 'Hair colour', 9000),
('Balyage', 'Hair colour', 8000),
('Omre', 'Hair colour', 8000),

-- Threading service
('Upper lips (Threading)', 'Threading', 20),
('Chin (Threading)', 'Threading', 30),
('Side lock (Threading)', 'Threading', 50),
('Eyebrow + forehead', 'Threading', 50),
('Full face (Threading)', 'Threading', 150),

-- Clean up
('Basic Clean up', 'Clean up', 800),
('Premium Clean up', 'Clean up', 1000),

-- Facial
('Basic Facial', 'Facial', 1000),
('AHA BHA Facial', 'Facial', 1500),
('Hydra facial', 'Facial', 3000),
('Advance hydra facial', 'Facial', 5000),
('Korean glow with hydra', 'Facial', 5000),
('Korean glow', 'Facial', 3000),
('Pro bio french glow premium', 'Facial', 4000),
('Super white treatment', 'Facial', 5000),

-- Skeyndor service
('Cleanup (Skeyndor)', 'Skeyndor', 1000),
('Basic facial (Skeyndor)', 'Skeyndor', 2000),
('Expert cleaning pro (Skeyndor)', 'Skeyndor', 2500),
('Power c (Skeyndor)', 'Skeyndor', 4000),
('Power retinol (Skeyndor)', 'Skeyndor', 4000),
('Aquatherm (Skeyndor)', 'Skeyndor', 4000),
('Power oxygen (Skeyndor)', 'Skeyndor', 4000),

-- D-Tan
('Face D-Tan', 'D-Tan', 500),
('Underarms D-Tan', 'D-Tan', 200),
('Face & neck D-Tan', 'D-Tan', 600),
('Full hand D-Tan', 'D-Tan', 600),
('Front & back D-Tan', 'D-Tan', 700),
('Full leg D-Tan', 'D-Tan', 800),
('Full body D-Tan', 'D-Tan', 2500),

-- Wax (Rica/Gel)
('Upperlips Wax', 'Wax', 50),
('Chin Wax', 'Wax', 100),
('Side lock Wax', 'Wax', 150),
('Under arms Wax', 'Wax', 150),
('Face Wax', 'Wax', 500),
('Full hand Wax', 'Wax', 500),
('Full leg Wax', 'Wax', 1000),
('Front & back Wax', 'Wax', 700),
('Full body Wax', 'Wax', 3000),
('Bikini brazilian Wax', 'Wax', 1500),
('Bikini rica Wax', 'Wax', 1000),

-- Mani-pedi
('Manicure basic', 'Mani-pedi', 1200),
('Peducure basic', 'Mani-pedi', 1500),
('Manicure premium', 'Mani-pedi', 2000),
('Pedicure premium', 'Mani-pedi', 3000),

-- Hair spa (Shoulder length)
('Loreal hair spa', 'Hair spa', 1000),
('Instant hair spa', 'Hair spa', 1000),
('Wella hair spa', 'Hair spa', 2000),
('Shea butter hair spa', 'Hair spa', 2500),
('Schwarzkopf hair spa', 'Hair spa', 2500),
('Nashi hair spa', 'Hair spa', 3000),
('Korean hair spa', 'Hair spa', 4000),

-- Body polishing
('Body polishing', 'Body polishing', 3000),
('Dtan body polishing', 'Body polishing', 5000),

-- Body massage
('Body massage (15 min sauna & 30 min massage)', 'Body massage', 2000),
('Body masaage (60min)', 'Body massage', 4000),
('Premium massage with full body care', 'Body massage', 11000),

-- Hair treatment
('Dandruff treatment', 'Hair treatment', 1500),
('Hairfall treatment', 'Hair treatment', 1500),
('Protein treatment', 'Hair treatment', 4000),
('Smoothening', 'Hair treatment', 5000),
('Rebounding', 'Hair treatment', 5000),
('Keratin smooth', 'Hair treatment', 6000),
('Botox', 'Hair treatment', 6000),
('Brazillian botox', 'Hair treatment', 7000),
('Nano plastia', 'Hair treatment', 7000),

-- Nail's service
('Simple gel polish', 'Nails', 500),
('Gel polish with art', 'Nails', 700),
('Extension', 'Nails', 1000),
('Extension with art', 'Nails', 1200),
('Gel extension with diamond art work', 'Nails', 1500),
('Toe gel polish', 'Nails', 500),
('Toe gel extension', 'Nails', 1000),
('Simple cat eye', 'Nails', 1200);

INSERT INTO public.staff (name, gender, salary, commission_rate) VALUES 
('Rahul (Senior Stylist)', 'Male', 25000, 15),
('Priya (Beautician)', 'Female', 20000, 10),
('Amit (Hair Expert)', 'Male', 22000, 10);

INSERT INTO public.products (name, purchase_price, selling_price, current_stock) VALUES
-- Hair care: Nashi Argan
('Nashi Argan kit', 0, 0, 10),
('Nashi bloom kit', 0, 0, 10),
('Nashi bloom mist', 0, 0, 10),
('Nashi filler kit', 0, 0, 10),
('Nashi essential kit for hairfall', 0, 0, 10),
('Nashi mass solution for hair thickning', 0, 0, 10),
('Nashi armonia for dandruff', 0, 0, 10),

-- Hair care: Wella
('Color motion kit (Wella)', 0, 0, 10),
('Color brilliance kit (Wella)', 0, 0, 10),

-- Hair care: Brillare professional
('Dandruff kit (Brillare)', 0, 0, 10),
('Hairfall kit (Brillare)', 0, 0, 10),

-- Hair care: Other
('Keracare shampoo mask', 0, 0, 10),
('Probio living cream', 0, 0, 10),

-- Hair care: Loreal professional paris
('Vitamino color kit (Loreal)', 0, 0, 10),
('Liss umlimited kit (Loreal)', 0, 0, 10),
('Inforcer kit (Loreal)', 0, 0, 10),
('Xtenso care blue kit (Loreal)', 0, 0, 10),
('Xtenso care glod kit (Loreal)', 0, 0, 10),

-- Skin care: Skeyndor
('Power c kit (Skeyndor)', 0, 0, 10),
('Power hyaluronic kit (Skeyndor)', 0, 0, 10),
('Aquatherm (Skeyndor)', 0, 0, 10),
('Clear balance (Skeyndor)', 0, 0, 10),

-- Skin care: Cares derma
('Face wash (Cares derma)', 0, 0, 10),
('Sunacream (Cares derma)', 0, 0, 10),
('Moisturiser (Cares derma)', 0, 0, 10),
('Maintenance cream (Cares derma)', 0, 0, 10),

-- Skin care: Urban colour london
('Face wash (Urban colour)', 0, 0, 10),
('Sunscream (Urban colour)', 0, 0, 10),

-- Skin care: Age lock
('Day cream (Age lock)', 0, 0, 10),
('Night cream (Age lock)', 0, 0, 10),
('Serum (Age lock)', 0, 0, 10),
('Face wash (Age lock)', 0, 0, 10);

--------------------------------------------------------
-- 8. ENABLE REALTIME
--------------------------------------------------------
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime;
COMMIT;

ALTER PUBLICATION supabase_realtime ADD TABLE public.customers;
